#!/usr/bin/env python3
"""
ig_obsidian_archive.py
-----------------------
Builds an Obsidian archive of your own Instagram posts from two official
exports, without connecting any app to the account:

  1) Instagram "Download your information" export (JSON, High quality)
     -> images + caption + timestamp
  2) Meta Business Suite content export (CSV or XLSX)
     -> per-post metrics

The two sources share no ID, so the join happens on the publish timestamp
with a configurable tolerance. Ambiguous cases are NOT guessed: they end up
in a review CSV.

All options live in config/config.yaml. To override it:

    python ig_obsidian_archive.py --config /path/to/config.yaml

Semantic tagging uses Ollama (local or cloud, free): needs a reachable
Ollama server (default http://localhost:11434, override with OLLAMA_HOST).
For cloud models (tag suffixed "-cloud"): `ollama signin`.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import re
import shutil
import sys
import unicodedata
import urllib.error
import urllib.request
import zipfile
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    raise SystemExit(
        "[!] Missing pyyaml: activate the venv and run `pip install -r requirements.txt`."
    )

try:
    from zoneinfo import ZoneInfo
except ImportError:  # Python < 3.9
    ZoneInfo = None  # type: ignore


# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

# Model used for tagging, via Ollama (local or cloud). Free.
# Local: any tag pulled with `ollama pull <model>`.
# Cloud (needs `ollama signin`, runs on Ollama's servers): tag with a
# "-cloud" suffix, e.g. "qwen3:235b-cloud", "gpt-oss:120b-cloud".
# Prefer non-reasoning models (llama3.2, mistral) over reasoning ones (qwen3,
# deepseek-r1): reasoning models burn hundreds of hidden "thinking" tokens
# per call before answering, which is pure latency for a bulk classification
# task like this and can blow past the request timeout.
DEFAULT_MODEL = "llama3.2:3b"

# Ollama server host. Defaults to the local one; can be pointed elsewhere via
# the OLLAMA_HOST env var. If OLLAMA_API_KEY is set it's sent as a Bearer
# token (only needed if talking directly to Ollama's cloud endpoint instead
# of a local instance that's already done `ollama signin`).
OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_API_KEY = os.environ.get("OLLAMA_API_KEY")

# Defaults for the `advanced` section of config.yaml. These rarely need
# changing per run (unlike metric/percentile/model), so they're not required
# fields, but they now live in config.yaml instead of only here.
DEFAULT_BATCH_SIZE = 15          # captions sent per Ollama call
DEFAULT_TOLERANCE_MINUTES = 90   # tolerance for the export<->insights join
DEFAULT_INSIGHTS_TZ = "America/Los_Angeles"  # Meta Business Suite exports in Pacific Time
DEFAULT_TIER_SCOPE = "year"      # performance tiers computed year by year
DEFAULT_ONLY_TOP = True          # only write notes for posts in the top tier
DEFAULT_ATTACHMENTS_DIRNAME = "attachments"

# Possible locations of the posts JSON inside the export, depending on the
# export version generated by Meta.
POSTS_JSON_CANDIDATES = [
    "your_instagram_activity/media/posts_1.json",
    "your_instagram_activity/content/posts_1.json",
    "media/posts_1.json",
    "content/posts_1.json",
]

# Extensions treated as images (videos are archived but not embedded as an
# image in the note).
IMAGE_EXT = {".jpg", ".jpeg", ".png", ".webp", ".heic"}


# --------------------------------------------------------------------------
# Utilities
# --------------------------------------------------------------------------

def fix_mojibake(s: str) -> str:
    """
    The Instagram export serializes UTF-8 strings as if they were latin-1:
    apostrophes and accents turn into garbage, emoji become mangled bytes.
    This turns them back. If the string is already correct, it's left as-is.
    """
    if not s:
        return s
    try:
        candidate = s.encode("latin-1").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return s
    # If the round-trip produced replacement characters, keep the original:
    # it means it wasn't mojibake.
    if "�" in candidate:
        return s
    return candidate


def slugify(text: str, max_len: int = 60) -> str:
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = re.sub(r"[^\w\s-]", "", text).strip().lower()
    text = re.sub(r"[\s_-]+", "-", text)
    return text[:max_len].strip("-") or "post"


def yaml_quote(value: Any) -> str:
    """Serializes a scalar value for the YAML frontmatter."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    s = str(value)
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def log(msg: str) -> None:
    print(msg, file=sys.stderr)


# --------------------------------------------------------------------------
# Data model
# --------------------------------------------------------------------------

@dataclass
class Post:
    key: str                        # stable identifier, derived from the timestamp
    timestamp: datetime             # UTC
    caption: str
    media: list[Path] = field(default_factory=list)   # absolute paths inside the export
    metrics: dict[str, float] = field(default_factory=dict)
    tags: dict[str, list[str]] = field(default_factory=dict)
    permalink: str | None = None
    tier: str | None = None
    match_note: str | None = None   # warnings about the join

    @property
    def is_carousel(self) -> bool:
        return len(self.media) > 1

    @property
    def title(self) -> str:
        first_line = self.caption.strip().splitlines()[0] if self.caption.strip() else ""
        first_line = re.sub(r"#\S+", "", first_line).strip()
        if not first_line:
            return self.timestamp.strftime("Post from %Y-%m-%d")
        return first_line[:70]


# --------------------------------------------------------------------------
# 1. Reading the Instagram export
# --------------------------------------------------------------------------

def prepare_export(path: Path, workdir: Path) -> Path:
    """Extracts it if it's a ZIP, otherwise returns the folder as-is."""
    if path.is_dir():
        return path
    if path.suffix.lower() != ".zip":
        raise SystemExit(f"[!] ig_export must be a .zip or a folder: {path}")
    dest = workdir / "ig_export"
    stamp = workdir / "ig_export.zip.mtime"
    current_mtime = path.stat().st_mtime
    if dest.exists():
        if stamp.exists() and stamp.read_text() == str(current_mtime):
            log(f"[i] Export already extracted in {dest}, reusing.")
            return dest
        shutil.rmtree(dest)
    log(f"[i] Extracting {path.name} ...")
    dest.mkdir(parents=True, exist_ok=True)
    failed = 0
    with zipfile.ZipFile(path) as zf:
        for inf in zf.infolist():
            # Undownloaded/placeholder entries: skip and move on. Notes are
            # still generated, just missing some media.
            try:
                zf.extract(inf, dest)
            except (OSError, zipfile.BadZipFile):
                failed += 1
    if failed:
        log(f"[!] {failed} file(s) not extracted (undownloaded placeholders?): "
            f"the corresponding notes will be missing media.")
    stamp.write_text(str(current_mtime))
    return dest


def find_posts_json(root: Path) -> Path:
    for rel in POSTS_JSON_CANDIDATES:
        p = root / rel
        if p.exists():
            return p
    # Fallback: look everywhere for a posts_*.json
    matches = sorted(root.rglob("posts_1.json")) or sorted(root.rglob("posts_*.json"))
    if matches:
        return matches[0]
    raise SystemExit(
        "[!] Can't find the posts JSON inside the export.\n"
        "    Make sure you picked the JSON format (not HTML) when downloading."
    )


def parse_ig_export(root: Path) -> list[Post]:
    posts_json = find_posts_json(root)
    log(f"[i] Reading {posts_json.relative_to(root)}")
    with open(posts_json, "r", encoding="utf-8") as f:
        raw = json.load(f)

    if isinstance(raw, dict):
        # Some export versions wrap the list in a key
        for key in ("posts", "media", "ig_posts"):
            if key in raw and isinstance(raw[key], list):
                raw = raw[key]
                break
        else:
            raise SystemExit("[!] Unrecognized posts JSON structure.")

    posts: list[Post] = []
    for entry in raw:
        media_items = entry.get("media") or []
        if not media_items:
            continue

        # Caption: at the post level for carousels, inside the first media
        # item for single posts.
        caption = entry.get("title") or ""
        if not caption and media_items:
            caption = media_items[0].get("title") or ""
        caption = fix_mojibake(caption)

        ts_raw = entry.get("creation_timestamp") or media_items[0].get("creation_timestamp")
        if not ts_raw:
            continue
        ts = datetime.fromtimestamp(int(ts_raw), tz=timezone.utc)

        paths = []
        for m in media_items:
            uri = m.get("uri")
            if not uri:
                continue
            p = root / uri
            if p.exists():
                paths.append(p)
            else:
                # Some exports nest content under a subfolder; fall back to
                # searching the whole export tree by filename.
                alt = next(root.rglob(Path(uri).name), None)
                if alt:
                    paths.append(alt)

        if not paths:
            continue

        posts.append(Post(key=str(int(ts_raw)), timestamp=ts, caption=caption, media=paths))

    posts.sort(key=lambda p: p.timestamp)
    log(f"[i] Found {len(posts)} post(s) in the export.")
    return posts


# --------------------------------------------------------------------------
# 2. Reading Meta Business Suite insights
# --------------------------------------------------------------------------

# Possible column names, lowercased. Meta's export locale follows the
# account's UI language, not a fixed one, so each maps several observed
# header spellings.
COLUMN_ALIASES = {
    "publish_time": [
        "publish time", "ora di pubblicazione", "data di pubblicazione",
        "orario di pubblicazione", "date", "data",
    ],
    "permalink": ["permalink", "link permanente", "link", "url"],
    "description": ["description", "descrizione", "didascalia", "caption", "titolo del post"],
    "reach": ["reach", "copertura", "account raggiunti", "accounts reached"],
    "impressions": ["impressions", "impressioni", "visualizzazioni", "views"],
    "likes": ["likes", "mi piace", "like"],
    "comments": ["comments", "commenti"],
    "shares": ["shares", "condivisioni"],
    "saves": ["saves", "salvataggi", "elementi salvati"],
    "follows": ["follows", "nuovi follower", "segui"],
    "engagement": ["engagement", "interazioni", "interazioni con i contenuti"],
}


def load_table(path: Path) -> tuple[list[str], list[list[str]]]:
    """Loads CSV or XLSX, returning (header, rows)."""
    suffix = path.suffix.lower()
    if suffix in (".csv", ".tsv", ".txt"):
        # Meta exports in UTF-8, sometimes with a BOM
        with open(path, "r", encoding="utf-8-sig", newline="") as f:
            sample = f.read(8192)
            f.seek(0)
            try:
                dialect = csv.Sniffer().sniff(sample, delimiters=",;\t")
            except csv.Error:
                dialect = csv.excel
            rows = [r for r in csv.reader(f, dialect) if any(c.strip() for c in r)]
    elif suffix in (".xlsx", ".xlsm"):
        try:
            from openpyxl import load_workbook
        except ImportError:
            raise SystemExit("[!] Needs openpyxl to read .xlsx files:  pip install openpyxl")
        wb = load_workbook(path, read_only=True, data_only=True)
        ws = wb[wb.sheetnames[0]]
        rows = []
        for r in ws.iter_rows(values_only=True):
            if r is None or all(c is None or str(c).strip() == "" for c in r):
                continue
            rows.append(["" if c is None else str(c) for c in r])
    else:
        raise SystemExit(f"[!] Unsupported insights format: {suffix}")

    if not rows:
        raise SystemExit("[!] The insights file is empty.")

    # Meta sometimes prepends decorative header rows: look for the first row
    # that contains a column recognizable as a date.
    header_idx = 0
    for i, row in enumerate(rows[:10]):
        lowered = [c.strip().lower() for c in row]
        if any(alias in lowered for alias in COLUMN_ALIASES["publish_time"]):
            header_idx = i
            break
    return rows[header_idx], rows[header_idx + 1:]


def map_columns(header: list[str]) -> dict[str, int]:
    lowered = [h.strip().lower() for h in header]
    mapping: dict[str, int] = {}
    for canonical, aliases in COLUMN_ALIASES.items():
        for alias in aliases:
            if alias in lowered:
                mapping[canonical] = lowered.index(alias)
                break
        else:
            # partial match as a safety net
            for i, h in enumerate(lowered):
                if any(alias in h for alias in aliases):
                    mapping[canonical] = i
                    break
    return mapping


DATE_FORMATS = [
    "%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%d",
    "%d/%m/%Y %H:%M:%S", "%d/%m/%Y %H:%M", "%d/%m/%Y",
    "%m/%d/%Y %H:%M:%S", "%m/%d/%Y %H:%M", "%m/%d/%Y",
    "%Y-%m-%dT%H:%M:%S",
]


def parse_datetime(value: str, tz: Any) -> datetime | None:
    value = value.strip()
    if not value:
        return None
    value = re.sub(r"\s*(UTC|GMT)[+-]?\d*$", "", value).strip()
    for fmt in DATE_FORMATS:
        try:
            naive = datetime.strptime(value, fmt)
            return naive.replace(tzinfo=tz).astimezone(timezone.utc)
        except ValueError:
            continue
    return None


def to_float(value: str) -> float:
    value = (value or "").strip().replace(".", "").replace(",", ".")
    value = re.sub(r"[^\d.\-]", "", value)
    try:
        return float(value)
    except ValueError:
        return 0.0


INSIGHTS_EXT = {".csv", ".tsv", ".txt", ".xlsx", ".xlsm"}


def discover_insight_files(insights_dir: Path) -> list[Path]:
    """One file per year inside insights_dir, auto-discovered."""
    if not insights_dir.exists():
        raise SystemExit(f"[!] Insights folder not found: {insights_dir}")
    files = sorted(p for p in insights_dir.iterdir() if p.suffix.lower() in INSIGHTS_EXT)
    if not files:
        raise SystemExit(
            f"[!] No insights file (.csv/.tsv/.xlsx) in {insights_dir}."
        )
    return files


def parse_insights(paths: list[Path], tz: Any) -> list[dict[str, Any]]:
    """
    Reads one or more insights files and merges their rows.
    Meta caps exports to short time windows (often a year), so it's normal
    to pass several. Duplicate rows across overlapping exports are dropped.
    """
    records: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()

    for path in paths:
        header, rows = load_table(path)
        cols = map_columns(header)
        if "publish_time" not in cols:
            raise SystemExit(
                f"[!] Can't find a publish-date column in {path.name}.\n"
                f"    Columns read: {header}\n"
                "    Rename the date column to 'Publish time' and try again."
            )

        added = 0
        for row in rows:
            def cell(name: str) -> str:
                i = cols.get(name)
                return row[i] if i is not None and i < len(row) else ""

            dt = parse_datetime(cell("publish_time"), tz)
            if dt is None:
                continue

            permalink = cell("permalink").strip() or None
            dedup_key = (permalink or "", dt.isoformat())
            if dedup_key in seen:
                continue
            seen.add(dedup_key)

            metrics = {
                m: to_float(cell(m))
                for m in ("reach", "impressions", "likes", "comments",
                          "shares", "saves", "follows", "engagement")
                if m in cols
            }
            if not metrics.get("engagement"):
                metrics["engagement"] = sum(
                    metrics.get(k, 0.0) for k in ("likes", "comments", "shares", "saves")
                )
            # Derived metric: interactions relative to reach. Lets posts from
            # different years be compared without penalizing ones published
            # when the page was smaller.
            if metrics.get("reach"):
                metrics["engagement_rate"] = round(
                    metrics["engagement"] / metrics["reach"] * 100, 2
                )

            records.append({
                "publish_time": dt,
                "permalink": permalink,
                "description": fix_mojibake(cell("description")),
                "metrics": metrics,
            })
            added += 1
        log(f"[i] {path.name}: {added} usable row(s).")

    log(f"[i] Total insights after dedup: {len(records)} row(s).")
    return records


# --------------------------------------------------------------------------
# 3. Timestamp join
# --------------------------------------------------------------------------

def join_posts(posts: list[Post], insights: list[dict[str, Any]],
               tolerance_min: int) -> list[dict[str, Any]]:
    """
    Matches each insights row to the closest post in time.
    Ambiguous cases are flagged, not resolved automatically.
    """
    tol = timedelta(minutes=tolerance_min)
    review: list[dict[str, Any]] = []
    used: set[str] = set()

    for rec in insights:
        candidates = [p for p in posts if abs(p.timestamp - rec["publish_time"]) <= tol]

        if not candidates:
            review.append({
                "issue": "no matching post",
                "insights_publish_time": rec["publish_time"].isoformat(),
                "permalink": rec["permalink"] or "",
                "description": rec["description"][:80],
            })
            continue

        if len(candidates) > 1:
            # Try to disambiguate by comparing the description, if present
            desc = (rec["description"] or "").strip().lower()
            if desc:
                scored = sorted(
                    candidates,
                    key=lambda p: _similarity(desc, p.caption.strip().lower()),
                    reverse=True,
                )
                best, second = scored[0], scored[1]
                if _similarity(desc, best.caption.lower()) - \
                   _similarity(desc, second.caption.lower()) > 0.25:
                    candidates = [best]

        if len(candidates) > 1:
            review.append({
                "issue": f"{len(candidates)} posts in the same time window",
                "insights_publish_time": rec["publish_time"].isoformat(),
                "permalink": rec["permalink"] or "",
                "description": rec["description"][:80],
                "candidates": " | ".join(p.timestamp.isoformat() for p in candidates),
            })
            for p in candidates:
                p.match_note = "ambiguous join: metrics not assigned, see review.csv"
            continue

        post = candidates[0]
        if post.key in used:
            review.append({
                "issue": "post already matched to another row",
                "insights_publish_time": rec["publish_time"].isoformat(),
                "permalink": rec["permalink"] or "",
                "description": rec["description"][:80],
            })
            continue

        post.metrics = rec["metrics"]
        post.permalink = rec["permalink"]
        used.add(post.key)

    matched = len(used)
    log(f"[i] Join: {matched}/{len(posts)} post(s) with metrics, "
        f"{len(review)} row(s) to review.")
    return review


def _similarity(a: str, b: str) -> float:
    """Jaccard over words, enough to disambiguate two posts."""
    sa, sb = set(a.split()), set(b.split())
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / len(sa | sb)


# --------------------------------------------------------------------------
# 4. Performance tiers
# --------------------------------------------------------------------------

def assign_tiers(posts: list[Post], metric: str, top_pct: float,
                 scope: str = "global") -> None:
    """
    Assigns performance tiers.

    scope='global' compares all posts against each other. Fine if the page
    has been stable, but if it grew, older posts all end up at the bottom
    for reasons of age, not quality.
    scope='year' computes the thresholds separately for each calendar year:
    the 'top' tier becomes "the best of that year".
    """
    def _tier_group(group: list[Post]) -> None:
        scored = [p for p in group if p.metrics.get(metric)]
        if not scored:
            for p in group:
                p.tier = "no-data"
            return
        values = sorted((p.metrics[metric] for p in scored), reverse=True)

        def percentile_cut(pct: float) -> float:
            idx = max(0, min(len(values) - 1, int(len(values) * pct / 100) - 1))
            return values[idx]

        top_cut = percentile_cut(top_pct)
        mid_cut = percentile_cut(50)

        for p in group:
            v = p.metrics.get(metric)
            if v is None:
                p.tier = "no-data"
            elif v >= top_cut:
                p.tier = "top"
            elif v >= mid_cut:
                p.tier = "good"
            else:
                p.tier = "average"

    if not any(p.metrics.get(metric) for p in posts):
        log(f"[!] No post has the metric '{metric}': skipping tiers.")
        log(f"    Available metrics: "
            f"{sorted({k for p in posts for k in p.metrics}) or 'none'}")
        return

    if scope == "year":
        by_year: dict[int, list[Post]] = {}
        for p in posts:
            by_year.setdefault(p.timestamp.year, []).append(p)
        for year, group in sorted(by_year.items()):
            _tier_group(group)
            n = sum(1 for p in group if p.tier == "top")
            log(f"[i] {year}: {n} post(s) in the top tier out of {len(group)}.")
    else:
        _tier_group(posts)
        n_top = sum(1 for p in posts if p.tier == "top")
        log(f"[i] Tiers assigned on '{metric}' (global scope): "
            f"{n_top} post(s) in the top tier.")


# --------------------------------------------------------------------------
# 5. Semantic tagging
# --------------------------------------------------------------------------

def axis_names(taxonomy: dict[str, Any]) -> list[str]:
    """Axes are the keys that don't start with an underscore."""
    return [k for k in taxonomy if not k.startswith("_")]


def axis_values(spec: dict[str, Any]) -> list[str]:
    return spec.get("values") or spec.get("valori") or []


def axis_description(spec: dict[str, Any]) -> str:
    return spec.get("description") or spec.get("descrizione") or ""


DEFAULT_INSTRUCTIONS = [
    "You are an archivist cataloguing posts from a page about space exploration.",
    "For each caption, assign the correct values for every axis of the taxonomy below.",
    "",
    "RULES:",
    "- Use ONLY the listed values. Never invent new ones.",
    "- If an axis cannot be determined from the caption, return an empty list [].",
    "- Ignore hashtags: they carry no information.",
]


def build_tagging_prompt(taxonomy: dict[str, Any]) -> str:
    # Instructions live in the JSON so you can change them (and their
    # language) without touching the code.
    instructions = taxonomy.get("_instructions") or DEFAULT_INSTRUCTIONS
    if isinstance(instructions, str):
        instructions = instructions.splitlines()
    lines = list(instructions) + ["", "TAXONOMY:"]

    axes = axis_names(taxonomy)
    for axis in axes:
        spec = taxonomy[axis]
        card = "multiple values allowed" if spec.get("multi") else "at most one value"
        lines.append(f"- {axis} ({card}): {axis_description(spec)}")
        lines.append(f"  values: {', '.join(axis_values(spec))}")

    lines += [
        "",
        "Respond ONLY with a JSON array, one object per caption, in the same",
        "order received, in this format:",
        '[{"id": "<received id>", ' + ", ".join(f'"{a}": []' for a in axes) + "}]",
        "No text before or after. No markdown fences.",
    ]
    return "\n".join(lines)


def clean_caption(caption: str, max_chars: int = 1200) -> str:
    text = re.sub(r"#\S+", "", caption)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text[:max_chars]


def ollama_chat(model: str, system: str, user: str) -> str:
    """Calls Ollama's /api/chat (local or cloud) and returns the response text."""
    body = json.dumps({
        "model": model,
        "stream": False,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    }).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if OLLAMA_API_KEY:
        headers["Authorization"] = f"Bearer {OLLAMA_API_KEY}"
    req = urllib.request.Request(
        f"{OLLAMA_HOST}/api/chat", data=body, headers=headers, method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise SystemExit(
            f"[!] Can't reach Ollama at {OLLAMA_HOST} ({exc}).\n"
            "    Local: start the server with `ollama serve`.\n"
            "    Cloud: run `ollama signin` (tags with -cloud suffix), "
            "or set OLLAMA_HOST/OLLAMA_API_KEY for the direct cloud endpoint."
        )
    return data["message"]["content"]


def tag_posts(posts: list[Post], taxonomy: dict[str, Any], model: str,
              batch_size: int, cache_path: Path) -> None:
    cache: dict[str, dict[str, list[str]]] = {}
    if cache_path.exists():
        cache = json.loads(cache_path.read_text(encoding="utf-8"))

    axes = axis_names(taxonomy)
    valid = {a: set(axis_values(taxonomy[a])) for a in axes}
    system = build_tagging_prompt(taxonomy)

    todo = []
    for p in posts:
        digest = hashlib.sha1(clean_caption(p.caption).encode()).hexdigest()[:16]
        if digest in cache:
            p.tags = cache[digest]
        elif clean_caption(p.caption):
            todo.append((digest, p))

    if not todo:
        log("[i] All tags were already cached.")
        return

    log(f"[i] To tag: {len(todo)} post(s) in {(len(todo) + batch_size - 1)//batch_size} call(s).")

    for start in range(0, len(todo), batch_size):
        batch = todo[start:start + batch_size]
        payload = [
            {"id": digest, "caption": clean_caption(p.caption)}
            for digest, p in batch
        ]
        try:
            text = ollama_chat(model, system, json.dumps(payload, ensure_ascii=False))
            text = re.sub(r"^```(?:json)?|```$", "", text.strip(),
                          flags=re.MULTILINE).strip()
            parsed = json.loads(text)
        except SystemExit:
            raise
        except Exception as exc:  # noqa: BLE001
            log(f"[!] Batch {start//batch_size + 1} failed ({exc}). Skipping it.")
            continue

        by_id = {str(item.get("id")): item for item in parsed if isinstance(item, dict)}
        for digest, post in batch:
            item = by_id.get(digest)
            if not item:
                continue
            tags: dict[str, list[str]] = {}
            for axis in axes:
                raw = item.get(axis) or []
                if isinstance(raw, str):
                    raw = [raw]
                kept = [v for v in raw if v in valid[axis]]
                if not taxonomy[axis].get("multi"):
                    kept = kept[:1]
                tags[axis] = kept
            post.tags = tags
            cache[digest] = tags

        cache_path.write_text(json.dumps(cache, ensure_ascii=False, indent=1),
                              encoding="utf-8")
        log(f"    batch {start//batch_size + 1} ok")


# --------------------------------------------------------------------------
# 6. Obsidian note generation
# --------------------------------------------------------------------------

def write_notes(posts: list[Post], out_dir: Path, attachments_name: str,
                only_top: bool) -> int:
    notes_dir = out_dir / "posts"
    att_dir = out_dir / attachments_name
    notes_dir.mkdir(parents=True, exist_ok=True)
    att_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    for post in posts:
        if only_top and post.tier not in ("top", None):
            continue

        date_str = post.timestamp.strftime("%Y-%m-%d")
        stem = f"{date_str}-{slugify(post.title)}"
        note_path = notes_dir / f"{stem}.md"

        # Copy media and build the embeds
        embeds = []
        for i, src in enumerate(post.media, 1):
            ext = src.suffix.lower()
            dest_name = f"{stem}-{i:02d}{ext}" if len(post.media) > 1 else f"{stem}{ext}"
            dest = att_dir / dest_name
            if not dest.exists():
                shutil.copy2(src, dest)
            if ext in IMAGE_EXT:
                embeds.append(f"![[{dest_name}]]")
            else:
                embeds.append(f"[[{dest_name}]]")

        # Frontmatter
        fm: list[str] = ["---"]
        fm.append(f"date: {post.timestamp.strftime('%Y-%m-%d')}")
        fm.append(f"year: {post.timestamp.year}")
        fm.append(f"time: {post.timestamp.strftime('%H:%M')}")
        fm.append(f"type: {'carousel' if post.is_carousel else 'single'}")
        if post.permalink:
            fm.append(f"permalink: {yaml_quote(post.permalink)}")
        if post.tier:
            fm.append(f"tier: {post.tier}")
        for metric, value in sorted(post.metrics.items()):
            if metric == "engagement_rate":
                fm.append(f"{metric}: {value}")
            else:
                fm.append(f"{metric}: {int(value)}")

        all_tags = ["post"]
        for axis, values in post.tags.items():
            for v in values:
                all_tags.append(f"{axis}/{v}")
        if post.tier:
            all_tags.append(f"tier/{post.tier}")
        fm.append("tags:")
        for t in all_tags:
            fm.append(f"  - {t}")
        fm.append("---")

        body = ["", f"# {post.title}", ""]
        body += embeds
        # The caption goes in a code block for two reasons: hashtags inside
        # it would otherwise get indexed by Obsidian as real tags (polluting
        # the taxonomy), and this way it's copyable with one click when you
        # want to repost.
        body += ["", "## Caption", "", "```text",
                 post.caption.strip() or "(no caption)", "```", ""]
        if post.match_note:
            body += ["> [!warning] Needs review", f"> {post.match_note}", ""]
        if post.permalink:
            body += [f"[Open on Instagram]({post.permalink})", ""]

        note_path.write_text("\n".join(fm + body), encoding="utf-8")
        written += 1

    return written


def write_index(posts: list[Post], out_dir: Path, taxonomy: dict[str, Any]) -> None:
    """Creates an index note with ready-to-use Dataview queries."""
    axes = axis_names(taxonomy)
    primary = axes[0] if axes else "program"
    secondary = axes[-1] if len(axes) > 1 else primary
    primary_vals = axis_values(taxonomy.get(primary, {}))
    secondary_vals = axis_values(taxonomy.get(secondary, {}))
    example_primary = primary_vals[0] if primary_vals else "apollo"
    example_secondary = secondary_vals[0] if secondary_vals else "anecdote"

    lines = [
        "---",
        "tags:",
        "  - index",
        "---",
        "",
        "# Post Archive",
        "",
        "> Requires the **Dataview** plugin (Settings -> Community plugins).",
        "",
        "## Best of each year",
        "",
        "```dataview",
        "TABLE date, engagement, engagement_rate, tags",
        'FROM "posts"',
        'WHERE tier = "top"',
        "SORT year DESC, engagement DESC",
        "```",
        "",
        f"## What I've already covered, by {primary}",
        "",
        "```dataview",
        "TABLE length(rows) AS count, max(rows.engagement) AS peak",
        'FROM "posts"',
        "FLATTEN tags AS tag",
        f'WHERE startswith(tag, "{primary}/")',
        "GROUP BY tag",
        "SORT count DESC",
        "```",
        "",
        "## Content gaps",
        "",
        f"What I've covered on `{example_primary}` without ever using the "
        f"`{example_secondary}` angle. Swap the two values to see what's missing.",
        "",
        "```dataview",
        "LIST",
        'FROM "posts"',
        f'WHERE contains(tags, "{primary}/{example_primary}")',
        f'  AND !contains(tags, "{secondary}/{example_secondary}")',
        "```",
        "",
        "## Worth reposting: old but strong",
        "",
        "```dataview",
        "TABLE year, engagement_rate, tags",
        'FROM "posts"',
        'WHERE tier = "top" AND year <= date(today).year - 2',
        "SORT engagement_rate DESC",
        "LIMIT 25",
        "```",
        "",
        "## Available axes",
        "",
    ]
    for axis in axes:
        vals = ", ".join(f"`#{axis}/{v}`" for v in axis_values(taxonomy[axis]))
        lines.append(f"- **{axis}**: {vals}")
    lines.append("")
    (out_dir / "Post Archive.md").write_text("\n".join(lines), encoding="utf-8")


def write_review(review: list[dict[str, Any]], out_dir: Path) -> None:
    if not review:
        return
    path = out_dir / "review.csv"
    fields = sorted({k for r in review for k in r})
    with open(path, "w", encoding="utf-8-sig", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(review)
    log(f"[!] {len(review)} row(s) to review by hand: {path}")


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def load_config(path: Path) -> dict[str, Any]:
    """Loads config/config.yaml. All script options live here."""
    if not path.exists():
        raise SystemExit(f"[!] Config not found: {path}")
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Builds an Obsidian archive from your own Instagram posts.",
    )
    ap.add_argument("--config", type=Path, default=Path("config/config.yaml"),
                    help="YAML config file (default: ./config/config.yaml)")
    args = ap.parse_args()

    cfg = load_config(args.config)
    paths = cfg.get("paths", {})
    tiers_cfg = cfg.get("tiers", {})
    tagging_cfg = cfg.get("tagging", {})
    advanced_cfg = cfg.get("advanced", {})

    try:
        ig_export = Path(paths["ig_export"])
        insights_dir = Path(paths["insights_dir"])
        out_base = Path(paths["out"])
    except KeyError as exc:
        raise SystemExit(f"[!] Missing 'paths.{exc.args[0]}' in {args.config}.")
    # Cache is keyed off the *base* out path (not the timestamped run folder
    # below), so the extracted export and the tag cache survive across runs.
    cache_dir = Path(paths.get("cache", out_base / ".ig_archive_cache"))
    taxonomy_path = Path(paths.get("taxonomy", "./config/taxonomy.json"))

    tag_model = tagging_cfg.get("model", DEFAULT_MODEL)
    tag_enabled = bool(tagging_cfg.get("enabled", True))
    batch_size = int(advanced_cfg.get("batch_size", DEFAULT_BATCH_SIZE))

    tier_metric = tiers_cfg.get("metric", "engagement")
    tier_top_pct = float(tiers_cfg.get("top_percentile", 25))

    tolerance_minutes = int(advanced_cfg.get("tolerance_minutes", DEFAULT_TOLERANCE_MINUTES))
    insights_tz_name = advanced_cfg.get("insights_tz", DEFAULT_INSIGHTS_TZ)
    tier_scope = advanced_cfg.get("tier_scope", DEFAULT_TIER_SCOPE)
    only_top = bool(advanced_cfg.get("only_top", DEFAULT_ONLY_TOP))
    attachments_dirname = advanced_cfg.get("attachments_dirname", DEFAULT_ATTACHMENTS_DIRNAME)

    if not ig_export.exists():
        raise SystemExit(f"[!] Instagram export not found: {ig_export}")
    if not taxonomy_path.exists():
        raise SystemExit(f"[!] Taxonomy not found: {taxonomy_path}")
    insight_files = discover_insight_files(insights_dir)

    if ZoneInfo is None:
        tz = timezone(timedelta(hours=1))
    else:
        try:
            tz = ZoneInfo(insights_tz_name)
        except Exception:  # noqa: BLE001
            log(f"[!] Timezone '{insights_tz_name}' not recognized, using UTC+1.")
            tz = timezone(timedelta(hours=1))

    # Each run gets its own timestamped output folder so a rerun never
    # overwrites a previous archive.
    run_stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    out_dir = out_base.parent / f"{out_base.name}-{run_stamp}"
    out_dir.mkdir(parents=True, exist_ok=True)
    workdir = cache_dir
    workdir.mkdir(parents=True, exist_ok=True)

    # 1. Instagram export
    root = prepare_export(ig_export, workdir)
    posts = parse_ig_export(root)
    if not posts:
        raise SystemExit("[!] No posts found in the export.")

    # 2. Insights + join
    insights = parse_insights(insight_files, tz)
    review = join_posts(posts, insights, tolerance_minutes)
    assign_tiers(posts, tier_metric, tier_top_pct, tier_scope)

    if only_top:
        posts = [p for p in posts if p.tier in ("top", None)]
        log(f"[i] only_top: {len(posts)} post(s) kept.")

    # 3. Tags
    taxonomy = json.loads(taxonomy_path.read_text(encoding="utf-8"))
    if not tag_enabled:
        log("[i] Tagging disabled by config: no semantic tags.")
    else:
        tag_posts(posts, taxonomy, tag_model, batch_size,
                  workdir / "tags_cache.json")

    # 4. Notes
    n = write_notes(posts, out_dir, attachments_dirname, only_top)
    write_index(posts, out_dir, taxonomy)
    write_review(review, out_dir)

    log(f"\n[OK] {n} note(s) written in {out_dir / 'posts'}")
    log(f"     Attachments in {out_dir / attachments_dirname}")
    log(f"     Open '{out_dir}' as a vault in Obsidian and start from 'Post Archive.md'.")


if __name__ == "__main__":
    main()
